# Generated by Django 4.0.1 on 2024-04-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='category',
            name='deleted',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
